name: certbot
run-name: get letsencrypt TLS certificates 
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */2 *"
jobs:
  certbot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install certbot
        run: |
          sudo snap install --classic certbot
          sudo ln -s /snap/bin/certbot /usr/bin/certbot
          sudo snap set certbot trust-plugin-with-root=ok
          sudo snap install certbot-dns-cloudflare
      - name: run certbot
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          DOMAIN: ${{ secrets.DOMAIN }}
        run: |
          echo "dns_cloudflare_api_token = $CF_API_TOKEN" > ./cftoken
          certbot certonly --dns-cloudflare --dns-cloudflare-credentials ./cftoken -d $DOMAIN --non-interactive
          rm ./cftoken
      - name: auto-push to github
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git diff-index --quiet HEAD || git commit -am "archived"
          git push